defmodule Moolah.Repo.Migrations.CreateBudgetCategories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:budget_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :icon, :text, null: false
      add :color, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:budget_categories, [:name], name: "budget_categories_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:budget_categories, [:name],
                     name: "budget_categories_unique_name_index"
                   )

    drop table(:budget_categories)
  end
end
