defmodule Moolah.Repo.Migrations.AddAccountTypeToLedgerAccounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ledger_accounts) do
      add :account_type, :text, null: true
    end

    # Update existing accounts with a default account type
    execute "UPDATE ledger_accounts SET account_type = 'bank_account' WHERE account_type IS NULL"

    alter table(:ledger_accounts) do
      modify :account_type, :text, null: false
    end
  end

  def down do
    alter table(:ledger_accounts) do
      remove :account_type
    end
  end
end
