defmodule Moolah.Repo.Migrations.CreateLifeAreaCategories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:life_area_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :icon, :text, null: false
      add :color, :text, null: false
      add :transaction_type, :text, null: false
      add :depth, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :parent_id,
          references(:life_area_categories,
            column: :id,
            name: "life_area_categories_parent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create unique_index(:life_area_categories, [:name, :parent_id],
             name: "life_area_categories_unique_name_per_parent_index"
           )
  end

  def down do
    drop_if_exists unique_index(:life_area_categories, [:name, :parent_id],
                     name: "life_area_categories_unique_name_per_parent_index"
                   )

    drop constraint(:life_area_categories, "life_area_categories_parent_id_fkey")

    drop table(:life_area_categories)
  end
end
