defmodule Moolah.Repo.Migrations.AddTransactionResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:transactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :transaction_type, :text, null: false
      add :amount, :money_with_currency, null: false
      add :source_amount, :money_with_currency
      add :description, :text
      add :date, :date, null: false, default: fragment("CURRENT_DATE")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :account_id,
          references(:ledger_accounts,
            column: :id,
            name: "transactions_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :target_account_id,
          references(:ledger_accounts,
            column: :id,
            name: "transactions_target_account_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :budget_category_id,
          references(:budget_categories,
            column: :id,
            name: "transactions_budget_category_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :life_area_category_id,
          references(:life_area_categories,
            column: :id,
            name: "transactions_life_area_category_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :transfer_id,
          references(:ledger_transfers,
            column: :id,
            name: "transactions_transfer_id_fkey",
            type: :binary,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:transactions, "transactions_account_id_fkey")

    drop constraint(:transactions, "transactions_target_account_id_fkey")

    drop constraint(:transactions, "transactions_budget_category_id_fkey")

    drop constraint(:transactions, "transactions_life_area_category_id_fkey")

    drop constraint(:transactions, "transactions_transfer_id_fkey")

    drop table(:transactions)
  end
end
