defmodule Moolah.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create_if_not_exists table(:investments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:investments) do
      add_if_not_exists :name, :text, null: false
      add_if_not_exists :type, :text, null: false
      add_if_not_exists :subtype, :text, null: false
      add_if_not_exists :initial_value, :money_with_currency, null: false
      add_if_not_exists :current_value, :money_with_currency, null: false
      add_if_not_exists :redemption_date, :date
      add_if_not_exists :purchase_date, :date

      add_if_not_exists :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add_if_not_exists :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add_if_not_exists :account_id, :uuid, null: false
    end

    create_if_not_exists unique_index(:investments, [:name],
                           name: "investments_unique_name_index"
                         )

    execute("""
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'investments_account_id_fkey'
      ) THEN
        ALTER TABLE investments
        ADD CONSTRAINT investments_account_id_fkey
        FOREIGN KEY (account_id)
        REFERENCES public.ledger_accounts(id);
      END IF;
    END
    $$;
    """)

    create_if_not_exists table(:investment_operations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:investment_operations) do
      add_if_not_exists :type, :text, null: false
      add_if_not_exists :value, :money_with_currency, null: false

      add_if_not_exists :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add_if_not_exists :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add_if_not_exists :investment_id, :uuid, null: false

      add_if_not_exists :transaction_id, :uuid
    end

    execute("""
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'investment_operations_investment_id_fkey'
      ) THEN
        ALTER TABLE investment_operations
        ADD CONSTRAINT investment_operations_investment_id_fkey
        FOREIGN KEY (investment_id)
        REFERENCES public.investments(id);
      END IF;

      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'investment_operations_transaction_id_fkey'
      ) THEN
        ALTER TABLE investment_operations
        ADD CONSTRAINT investment_operations_transaction_id_fkey
        FOREIGN KEY (transaction_id)
        REFERENCES public.transactions(id);
      END IF;
    END
    $$;
    """)

    create_if_not_exists table(:investment_histories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:investment_histories) do
      add_if_not_exists :value, :money_with_currency, null: false
      add_if_not_exists :recorded_on, :date, null: false

      add_if_not_exists :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add_if_not_exists :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add_if_not_exists :investment_id, :uuid, null: false
    end

    execute("""
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'investment_histories_investment_id_fkey'
      ) THEN
        ALTER TABLE investment_histories
        ADD CONSTRAINT investment_histories_investment_id_fkey
        FOREIGN KEY (investment_id)
        REFERENCES public.investments(id);
      END IF;
    END
    $$;
    """)

    alter table(:transactions) do
      add_if_not_exists :target_investment_id, :uuid
    end

    execute("""
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'transactions_target_investment_id_fkey'
      ) THEN
        ALTER TABLE transactions
        ADD CONSTRAINT transactions_target_investment_id_fkey
        FOREIGN KEY (target_investment_id)
        REFERENCES public.investments(id);
      END IF;
    END
    $$;
    """)
  end

  def down do
    drop_if_exists constraint(:investment_histories, "investment_histories_investment_id_fkey")
    drop_if_exists table(:investment_histories)

    drop_if_exists constraint(:investment_operations, "investment_operations_investment_id_fkey")
    drop_if_exists constraint(:investment_operations, "investment_operations_transaction_id_fkey")
    drop_if_exists table(:investment_operations)

    drop_if_exists unique_index(:investments, [:name], name: "investments_unique_name_index")
    drop_if_exists constraint(:investments, "investments_account_id_fkey")

    alter table(:investments) do
      remove_if_exists :account_id
      remove_if_exists :updated_at
      remove_if_exists :inserted_at
      remove_if_exists :purchase_date
      remove_if_exists :redemption_date
      remove_if_exists :current_value
      remove_if_exists :initial_value
      remove_if_exists :subtype
      remove_if_exists :type
      remove_if_exists :name
    end

    drop_if_exists constraint(:transactions, "transactions_target_investment_id_fkey")

    drop_if_exists table(:investments)

    alter table(:transactions) do
      remove_if_exists :target_investment_id
    end
  end
end
